Models/Cat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cat
    {
        [Required]
        public string Cat_ID { get; set; }
        [Required]
        public string Cat_name { get; set; }
        [Required]
        public string Decription { get; set; }
    }
}

Models/Detail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detail
    {
        [Required]
        public string Detail_ID { get; set; }
       
        public string Coures_ID { get; set; }

        public string Student_ID { get; set; }
   
        public virtual Coure Coure { get; set; }

        public virtual Student Student { get; set; }
    }
}

Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASM.Models;

namespace ASM.Controllers
{
    public class CatsController : Controller
    {
        private NLNEntities db = new NLNEntities();

        // GET: Cats
        public ActionResult Index()
        {
            return View(db.Cats.ToList());
        }

        // GET: Cats/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // GET: Cats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cat_ID,Cat_name,Decription")] Cat cat)
        {
            if (ModelState.IsValid)
            {
                db.Cats.Add(cat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cat);
        }

        // GET: Cats/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // POST: Cats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Cat_ID,Cat_name,Decription")] Cat cat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cat);
        }

        // GET: Cats/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // POST: Cats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Cat cat = db.Cats.Find(id);
            db.Cats.Remove(cat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASM.Models;

namespace ASM.Controllers
{
    public class DetailsController : Controller
    {
        private NLNEntities db = new NLNEntities();

        // GET: Details
        public ActionResult Index()
        {
            var details = db.Details.Include(d => d.Coure).Include(d => d.Student);
            return View(details.ToList());
        }

        // GET: Details/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // GET: Details/Create
        public ActionResult Create()
        {
            ViewBag.Coures_ID = new SelectList(db.Coures, "Course_ID", "Name");
            ViewBag.Student_ID = new SelectList(db.Students, "Students_ID", "Name");
            return View();
        }

        // POST: Details/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Detail_ID,Coures_ID,Student_ID")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Details.Add(detail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Coures_ID = new SelectList(db.Coures, "Course_ID", "Name", detail.Coures_ID);
            ViewBag.Student_ID = new SelectList(db.Students, "Students_ID", "Name", detail.Student_ID);
            return View(detail);
        }

        // GET: Details/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            ViewBag.Coures_ID = new SelectList(db.Coures, "Course_ID", "Name", detail.Coures_ID);
            ViewBag.Student_ID = new SelectList(db.Students, "Students_ID", "Name", detail.Student_ID);
            return View(detail);
        }

        // POST: Details/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Detail_ID,Coures_ID,Student_ID")] Detail detail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Coures_ID = new SelectList(db.Coures, "Course_ID", "Name", detail.Coures_ID);
            ViewBag.Student_ID = new SelectList(db.Students, "Students_ID", "Name", detail.Student_ID);
            return View(detail);
        }

        // GET: Details/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detail detail = db.Details.Find(id);
            if (detail == null)
            {
                return HttpNotFound();
            }
            return View(detail);
        }

        // POST: Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Detail detail = db.Details.Find(id);
            db.Details.Remove(detail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Cats/Create.cshtml
@model ASM.Models.Cat

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cat_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cat_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cat_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cat_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cat_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cat_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Decription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Decription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Decription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" submit" class="btn btn-primary btn-rounded width-md waves-effect waves-ligh" /> |
                <a href=' @Url.Action("Index","Cats")' class="btn btn-danger btn-rounded width-md waves-effect waves-light">Back To List </a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Cats/Delete.cshtml
@model ASM.Models.Cat

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cat_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cat_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Decription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Decription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger btn-rounded width-md waves-effect waves-light" /> |
    <a href='@Url.Action("Index","Cats")' class="btn btn-primary btn-rounded width-md waves-effect waves-ligh">Back To List </a>
</div>
    }
</div>

Views/Cats/Details.cshtml
@model ASM.Models.Cat

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cat_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cat_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Decription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Decription)
        </dd>

    </dl>
</div>
<p>

    <a href='@Url.Action("Edit", "Cats",new { id = Model.Cat_ID })' class="btn btn-primary btn-rounded width-md waves-effect waves-ligh">Edit</a> |
    <a href='@Url.Action("Index","Cats")' class="btn btn-danger btn-rounded width-md waves-effect waves-light">Back To List </a>
</p>

Views/Cats/Edit.cshtml
@model ASM.Models.Cat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Cat_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Cat_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cat_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cat_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Decription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Decription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Decription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
               
                <input type="submit" value=" Save" class="btn btn-primary btn-rounded width-md waves-effect waves-ligh" /> |
                <a href=' @Url.Action("Index","Cats")' class="btn btn-danger btn-rounded width-md waves-effect waves-light">Back To List </a>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Cats/Index.cshtml
@model IEnumerable<ASM.Models.Cat>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cat_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Decription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cat_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Decription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Cat_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Cat_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Cat_ID })
        </td>
    </tr>
}

</table>